/**
 *FouleFactoryApiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/14/2016
 */

'use strict';
angular.module('FouleFactoryApiLib',[]).factory('Configuration', function() {
    return {
        //The base Uri for API calls
        BASEURI : "http://api.foulefactory.com",

        //The username to use with basic authentication
        //TODO: Replace the basicAuthUserName with an appropriate value
        basicAuthUserName : "TODO: Replace",

        //The password to use with basic authentication
        //TODO: Replace the basicAuthPassword with an appropriate value
        basicAuthPassword : "TODO: Replace"

    };
});

